# Generated by Django 3.2.8 on 2022-07-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='bc',
        ),
        migrations.RemoveField(
            model_name='team',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='team',
            name='gagne',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mj',
        ),
        migrations.RemoveField(
            model_name='team',
            name='nul',
        ),
        migrations.RemoveField(
            model_name='team',
            name='perdu',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
    ]
