# Generated by Django 3.2.8 on 2022-08-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poulea',
            options={'verbose_name_plural': 'Match PouleA'},
        ),
        migrations.AlterModelOptions(
            name='pouleb',
            options={'verbose_name_plural': 'Match PouleB'},
        ),
        migrations.AlterModelOptions(
            name='teama',
            options={'verbose_name_plural': 'TeamA'},
        ),
        migrations.AlterModelOptions(
            name='teamb',
            options={'verbose_name_plural': 'TeamB'},
        ),
    ]
